name: Flutter CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.6'
          channel: stable

      - name: Install Packages
        run: flutter pub get

      - name: Analyze Code
        run: flutter analyze

      - name: Run Tests
        run: flutter test

      - name: Build APK
        run: flutter build apk

      - name: Build AppBundle
        run: flutter build appbundle

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk

      - name: Upload to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          token: ${{ secrets.FIREBASE_TOKEN }}
          groups: QA-Team
          file: build/app/outputs/flutter-apk/app-release.apk

      - name: Check Formatting
        run: dart format --output=none --set-exit-if-changed .

      - name: Print Secret
        shell: pwsh
        run: Write-Host "My name is $env:MY_NAME"
        env:
          MY_NAME: ${{ secrets.MY_NAME }}
